config/routes.rb
Rails.application.routes.draw do
  
  get 'order/index'
  get '/', to: 'sessions#welcome'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  delete '/logout', to: 'sessions#destroy'

  get '/auth/:provider/callback' => 'sessions#create'

  resources :milks
  resources :orders
  resources :reviews
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/milk.rb
# frozen_string_literal: true

class Milk < ApplicationRecord
  has_many :reviews, through: :milk
  has_many :orders, through: :user
end

app/models/order.rb
# frozen_string_literal: true

class Order < ApplicationRecord
  belongs_to :user
  has_many :milks

  validates :name, :frequency, :size, :milk_id, presence: true

  scope :longest_name, -> { order("COUNT(LENGTH(name)) desc").limit(1)} 

end

app/models/review.rb
# frozen_string_literal: true

class Review < ApplicationRecord
  belongs_to :milk

  validates :milk_id, :stars, :title, :content, presence: true

end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_many :reviews
  has_many :orders

  validates :email, uniqueness: true, presence: true, format: /\w+@\w+\.{1}[a-zA-Z]{2,}/

  has_secure_password

  scope :most_reviews, -> { select("users.id, COUNT(reviews.user_id) AS reviews_count")
      .joins(:reviews)
      .group(:id)
      .order(reviews_count: :desc)
  }

  def self.create_by_github_omniauth(auth)
    find_or_create_by(email: auth[:info][:email]) do |user|
      user.password_digest = SecureRandom.uuid
    end
  end

end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?

  def logged_in?
    !!session[:user_id]
  end

  def current_user
    @current_user ||= User.find_by_id(session[:user_id]) if session[:user_id]
  end

  def redirect_if_not_logged_in
    redirect_to login_path unless logged_in?
   end
end

app/controllers/milks_controller.rb
# frozen_string_literal: true

class MilksController < ApplicationController
  before_action :redirect_if_not_logged_in

  def index
    @milks = Milks.all
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :redirect_if_not_logged_in

  def index
    if @orders = Order.where(user_id: session[:user_id])
      @orders
    else
      @orders = Order.all
  end
end

  def new
    @order = Order.new
  end

  def create
   @order = current_user.orders.build(order_params)
    if @order.save
      redirect_to orders_url
    else
      flash[:error] = 'Error, please fill in all fields and try again.'
      render :new
    end
  end

  def edit
    selected_order(params[:id])
  end

  def update
    selected_order(params[:id])
    if @order.update_attributes(order_params)
      redirect_to orders_path
    else
      flash[:error] = 'Error, please try again.'
      render :edit
    end
  end

  def destroy
    selected_order(params[:id])
    @order.destroy
    redirect_to orders_path
  end

  def show
    selected_order(params[:id])
    @milk = Milk.find_by_id(@order.milk_id)
  end

  private

  def order_params
    params.require(:order).permit(:frequency, :size, :milk_id, :name)
   end

  def selected_order(id)
    @order = Order.find_by_id(id)
    @order
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :redirect_if_not_logged_in

  def new
    if @milk = Milk.find_by_id(params[:milk_id])
       @review = @milk.reviews.build
    else
      @review = Review.new
    end
  end

  def create
    @review = current_user.reviews.build(review_params)
    if @review.save
      redirect_to review_path(@review)
    else
      flash[:error] = 'Error, please fill in all fields and try again.'
      render :new
    end
  end

  def show
    @review = Review.find_by_id(params[:id])
    @milk = Milk.find_by_id(@review.milk_id)
  end

  def index
    @reviews = Review.all 
    @most_reviewed = User.most_reviews.first
    @most_reviewed = UsersHelper.getusername(@most_reviewed.id) 
  end

  private

  def review_params
    params.require(:review).permit(:milk_id, :content, :stars, :title)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def welcome
    if logged_in?
      @user = User.find(session[:user_id])
      redirect_to user_path(@user)
    end
    end

  def new; end

  def destroy
    session.delete(:user_id)
    redirect_to '/'
  end

  def create
    if params[:provider] == 'github'
      @user = User.create_by_github_omniauth(auth)
      puts @user
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      @user = User.find_by(email: params[:user][:email])
      if @user&.authenticate(params[:user][:password])
        session[:user_id] = @user.id
        redirect_to user_path(@user)
      else
        flash[:error] = 'Please enter correct e-mail address and password.'
        redirect_to login_path
        end
    end
    end

  private

  def auth
    request.env['omniauth.auth']
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      flash[:error] = 'Please enter correct e-mail address and password.'
      render :new
    end
  end

  def show
    @user = User.find_by_id(params[:id])
    redirect_to '/' unless @user
  end

  def index
    @most_reviewed = Review.most_reviews
    puts @most_reviewed
  end

  private

  def user_params
    params.require(:user).permit(:password, :email)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/milks_helper.rb
# frozen_string_literal: true

module MilksHelper
end

app/helpers/orders_helper.rb
# frozen_string_literal: true

module OrdersHelper
  def frequency_options
    %w[weekly bi-weekly monthly one-time]
  end

  def size_options
    ['1 gallon', '1/2 gallon', '1 Pint']
  end

  def self.getmilk(order_id)
    @order = Order.find(order_id)
    @order.milktype
  end
end

app/helpers/reviews_helper.rb
# frozen_string_literal: true

module ReviewsHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
  def self.getusername(user_id)
    @user = User.find(user_id)
    @user.email.partition('@').first
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Milkmaid</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <link href="../style.css" rel="stylesheet">
</head>


<nav class="navbar navbar-default navbar-static-top">
  <ul class="nav navbar-nav">
    <% if logged_in? %>
    <li> <%= link_to "Milkmaid", user_path(current_user.id) %> </li>
    <li> <%= link_to "Orders", orders_path %> </li>
    <li> <%= link_to "Reviews", reviews_path %> </li>
    <li><%= link_to "Log Out", logout_path, method: :delete  %></li>
    <% else %>
    <li> <%= link_to "Milkmaid", "/" %> </li>
    <% end %>
  </ul>

  <% if logged_in? %>
  <p class="navbar-text navbar-right" style="margin-right: 15px;">Signed in as (<%= current_user.email%>)</b></p>
  <% end %>
</nav>


<div class="container">
  <div class="row">
    <%= content_tag(:div, flash[:error], :class => "alert alert-warning") if flash[:error] %>
    <%= content_tag(:div, flash[:notice], :class => "alert alert-success") if flash[:notice] %>
    <%= content_tag(:div, flash[:alert], :class => "alert alert-danger") if flash[:alert] %>
    <div class="col-md-1"></div>
    <div class="col-md-10">
      <div class="jumbotron"><%= yield %>
      </div>
    </div>
    <div class="col-md-1"></div>
  </div>
</div>


</html>

app/views/orders/_form.html.erb
<%=  form_for(@order) do |f| %>
Name of Order: <%= f.text_field :name %><br>
How often would you like to receive your order?
<%=  f.select :frequency, frequency_options, prompt: true %><br>
Choose size:
<%= f.select :size, size_options, prompt: true %>
<br>
<%= f.label :milk_id, "Choose Milk:" %>
<%= f.collection_select :milk_id, Milk.all, :id, :milktype, prompt: true %>
<br>
<%= f.submit "Place order" %>

<% end %>

app/views/orders/edit.html.erb
<h4>Edit Order:</h4>

<%= render partial: 'form' %>

app/views/orders/index.html.erb
<% if @orders %>
  <% @orders.each_with_index do |order, index| %>
    <%= index+1 %>. <%= order.name %> <%= link_to "show", order_path(order) %> <br>
  <% end %>
<% else %><br>
  No orders currently placed.
<%end %>

<%= link_to "Place an Order", new_order_path %>

app/views/orders/new.html.erb
<h1> Place an order! </h1>
<div>
  <%= render partial: 'form' %>
</div>

app/views/orders/show.html.erb
<b>Order Name: </b><%= @order.name %><br>
<b>Milk Type:</b> <%=@milk.milktype %> <br>
<b>Milk Size: </b><%= @order.size %><br>
<b>Order Frequency: </b> <%= @order.frequency %><br>
<%= link_to "Edit", edit_order_path(@order) %>
<%= link_to "Cancel Order", order_path(@order), method: :delete %> 

app/views/reviews/index.html.erb
<% if @reviews %>
  <% @reviews.each_with_index do |review, index| %>
    <%= index+1 %>. <%= review.title %> -  <i><%= UsersHelper.getusername(review.user_id) %> </i>
    <%= link_to "More Details", review_path(review) %> 
    <br>
    <% end %>
  <% else %>
  <br>
Nothing to show.
<% end %>

<h4>User with most Reviews: <%=@most_reviewed%></h4>

<%= link_to "Leave a review", new_review_path %>

app/views/reviews/new.html.erb
<h1> Tell us how you felt! </h1>

<%= form_for(@review) do |f|%>
  <% if params[:milk_id] %>
    <%= f.hidden_field :milk_id %>
  <% else %>

    <div>
      <%= f.label :milk_id, "Select item to review" %>
      <%= f.collection_select :milk_id, Milk.all, :id, :milktype, include_blank: true %>
    </div>
  <% end %>

  <div>
    <%= f.label :stars %>
    <%= f.number_field :stars, min:0, max:5 %>
  </div>

  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div>
    <%= f.label :content %>
    <%= f.text_area :content %>
  </div>


  <%= f.submit %>

<% end %>

app/views/reviews/show.html.erb
<b>Review of:</b>  <%= @milk.milktype %> 
<br>
<b>Rating:</b>  <%= @review.stars %>
<br>
<b>Title:</b>  <%= @review.title %>
<br>
<b>Conent:</b>  <%= @review.content %>
<br>
<b>User: </b><%= UsersHelper.getusername(@review.user_id) %>
<br>
<%= link_to "All Reviews", reviews_path %>

app/views/users/index.html.erb
<%= link_to "Orders", orders_path %>  <br>
<%= link_to "Reviews", reviews_path %> <br>


<%= yield %>

app/views/users/new.html.erb
<h1> Sign Up! </h1>
<%= form_for(@user) do |f|%>

<%= f.label :email %>
<%= f.text_field :email %>
<%= f.label :password %>
<%= f.password_field :password %>

<%= f.submit "Sign Up" %>
<% end %>

app/views/users/show.html.erb
<h2>Welcome to Milkmaid!</h2>
<h4>We deliver milk to your door in environmentally friendly, reusable packaging. <br> We pick it up, too, to reduce waste. <br> Place an order or leave a review for a previous one! </h4>

<div>
  <div>
    <h3><%= link_to "Orders", orders_path %> </h3>
    <h3><%= link_to "Reviews", reviews_path %></h3>
    <%= yield %>
</div>